# Generated by Django 5.2.3 on 2025-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
