# Generated by Django 5.2.3 on 2025-06-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
