# Generated by Django 5.2.3 on 2025-06-21 14:33

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_available_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='product_images/', validators=[products.models.validate_svg]),
        ),
    ]
